In [1]:
import warnings ;warnings.filterwarnings('ignore')
import sys ;sys.path.append("../../")
from  CommonFunc_04 import *
DataPreprocessing.plotSetting(setting_info=True)
import tensorflow as tf
print(yellow(f"tensorflow version : {tf.__version__}"))
import tensorflow as tf, numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import keras

  ⁍ 현재 경로의 폴더 목록 --
  폴더1 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/images
  폴더2 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/__pycache__
  폴더3 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/model
  폴더4 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/Data
../ +  ../../ 경로 python path 에 추가. 
◎ 주피터 가상환경  : base
◎ Python 설치 경로:/opt/anaconda3/bin/python
◎ Graph 한글화 Setting
패키지 목록이 package_list.txt 파일에 저장되었습니다.
  - ◎ matplot graph set complete
tensorflow version : 2.16.1


텐서플로 데이터 셋 목록
- https://oreil.ly/zL7zq

In [2]:
# !pip install tensorflow-datasets

## Tensoflow data set 에서 fashion mnist 불러오기

In [3]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data =tfds.load("fashion_mnist")
for i in mnist_data:
    print(i)


train
test


In [4]:
mnist_train = tfds.load(name ='fashion_mnist' ,split='train')
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


## take 1 함수를 이요해서 안에 내용 까보기

In [5]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2024-10-17 09:13:59.583837: W tensorflow/core/kernels/data/cache_dataset_ops.cc:858] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2024-10-17 09:13:59.585564: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


> mnist train 은 dict 타입이고 item 은 image, label 로 되어있음.        
> image 항목은 tf.Tensor type 28*28 배열임.         
> 레이블 : tf.Tensor(2, shape=(), dtype=int64)      

## info 를 사용해서 설명 읽기

In [6]:
mnist_test ,info = tfds.load(name='fashion_mnist', with_info="true")
info

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/Users/forrestdpark/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
   

---
### 4.2 케라스 모델에서 텐서플로 데이터 셋 사용하기
- 케라스 데이터셋은 ndarray type 임. 텐서플로 데이터셋은 Dataset객체나 Tensor타입을 반환하기때문에 넘파이 배열로 바꾸려면 변환작업이 필요함 

In [9]:
mnist = tf.keras.datasets.fashion_mnist



> ### fashion mnist data 러닝

In [12]:
(training_images, training_labels),(test_images, test_labels)=\
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split  =['train','test'], ## split 을 하지않으면 dic 반환,
                            ## split 변수를 지정하면 분할 세트의 리스트가 반환됨. 
                            batch_size = -1, ## tf.Tensor 타입의 전체 데이터 반화
                            as_supervised =True 
                            ))


def model_training_for_tfds(training_images, training_labels,test_images, test_labels):
    ## 2024.10.17
    ## fashion mnist 인 경우 tf.unit8 타입의 텐서가 반환되기떄문에  cast 를 통해 실수로 변환후 255로 나누어야함. 
    training_images = tf.cast(training_images,tf.float32)/255.0
    test_images = tf.cast(test_images,tf.float32)/255.0
    
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape =(28,28,1)),
        tf.keras.layers.Dense(128, activation=tf.nn.relu),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10,activation=tf.nn.softmax)
        
    ])
    model.compile(optimizer = 'adam',
                  loss = 'sparse_categorical_crossentropy',
                  metrics = ['accuracy'])
    model.fit(training_images,training_labels, epochs=5)
model_training_for_tfds(training_images, training_labels,test_images, test_labels)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.7622 - loss: 0.6823
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - accuracy: 0.8515 - loss: 0.4124
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 848us/step - accuracy: 0.8654 - loss: 0.3720
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - accuracy: 0.8724 - loss: 0.3477
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.8788 - loss: 0.3276


> ### 말, 사람 분류 

In [ ]:
def hh_classification_tfds(
    h_act_f = 'relu',
    conv_n = 16,
    conv_s =(3,3),
    maxpool_s = (2,2)
    ):
    import tensorflow as tf
    import tensorflow_datasets as tfds
    data = tfds.load('horses_or_humans',
                     split='train',
                     as_supervised=True)
    train_batches = data.shuffle(100).batch(10)
    
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(conv_n,conv_s, activation = h_act_f,
                               input_shape = (300,300,3)),
        tf.keras.layers.
        
    ])