In [1]:
import warnings ;warnings.filterwarnings('ignore')
import sys ;sys.path.append("../../")
from  CommonFunc_04 import *
DataPreprocessing.plotSetting(setting_info=True)
import tensorflow as tf, numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
print(yellow(f"tensorflow version : {tf.__version__}"))



  ⁍ 현재 경로의 폴더 목록 --
  폴더1 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/images
  폴더2 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/__pycache__
  폴더3 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/model
  폴더4 :  /Users/forrestdpark/Desktop/PDG/DailyHelloWorld_/개발자를위한머신러닝/Data
../ +  ../../ 경로 python path 에 추가. 
◎ 주피터 가상환경  : base
◎ Python 설치 경로:/opt/anaconda3/bin/python
◎ Graph 한글화 Setting
패키지 목록이 package_list.txt 파일에 저장되었습니다.
  - ◎ matplot graph set complete
tensorflow version : 2.17.0


텐서플로 데이터 셋 목록
- https://oreil.ly/zL7zq

In [2]:
# !pip install tensorflow-datasets

## Tensoflow data set 에서 fashion mnist 불러오기

In [3]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data =tfds.load("fashion_mnist")
for i in mnist_data:
    print(i)


train
test


In [4]:
mnist_train = tfds.load(name ='fashion_mnist' ,split='train')
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


## take 1 함수를 이요해서 안에 내용 까보기

In [5]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2024-10-18 11:28:54.768648: W tensorflow/core/kernels/data/cache_dataset_ops.cc:913] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2024-10-18 11:28:54.770603: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


> mnist train 은 dict 타입이고 item 은 image, label 로 되어있음.        
> image 항목은 tf.Tensor type 28*28 배열임.         
> 레이블 : tf.Tensor(2, shape=(), dtype=int64)      

## info 를 사용해서 설명 읽기

In [6]:
mnist_test ,info = tfds.load(name='fashion_mnist', with_info="true")
info

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/Users/forrestdpark/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
   

---
# 4.2 케라스 모델에서 텐서플로 데이터 셋 사용하기
- 케라스 데이터셋은 ndarray type 임. 텐서플로 데이터셋은 Dataset객체나 Tensor타입을 반환하기때문에 넘파이 배열로 바꾸려면 변환작업이 필요함 

In [7]:
mnist = tf.keras.datasets.fashion_mnist



> ### fashion mnist data 러닝

In [8]:
(training_images, training_labels),(test_images, test_labels)=\
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split  =['train','test'], ## split 을 하지않으면 dic 반환,
                            ## split 변수를 지정하면 분할 세트의 리스트가 반환됨. 
                            batch_size = -1, ## tf.Tensor 타입의 전체 데이터 반화
                            as_supervised =True 
                            ))
def model_training_for_tfds(training_images, training_labels,test_images, test_labels):
    ## 2024.10.17
    ## fashion mnist 인 경우 tf.unit8 타입의 텐서가 반환되기떄문에  cast 를 통해 실수로 변환후 255로 나누어야함. 
    training_images = tf.cast(training_images,tf.float32)/255.0
    test_images = tf.cast(test_images,tf.float32)/255.0
    
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape =(28,28,1)),
        tf.keras.layers.Dense(128, activation=tf.nn.relu),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10,activation=tf.nn.softmax)
        
    ])
    model.compile(optimizer = 'adam',
                  loss = 'sparse_categorical_crossentropy',
                  metrics = ['accuracy'])
    model.fit(training_images,training_labels, epochs=5)
model_training_for_tfds(training_images, training_labels,test_images, test_labels)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 955us/step - accuracy: 0.7685 - loss: 0.6710
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 842us/step - accuracy: 0.8522 - loss: 0.4092
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 909us/step - accuracy: 0.8674 - loss: 0.3633
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 885us/step - accuracy: 0.8744 - loss: 0.3441
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 862us/step - accuracy: 0.8801 - loss: 0.3315


> ### 말, 사람 분류 

In [9]:
def hh_classification_tfds(
    h_act_f = 'relu',
    conv_n = 16,
    conv_s =(3,3),
    maxpool_s = (2,2)
    ):
    import tensorflow as tf
    import tensorflow_datasets as tfds
    ## training data load 
    data = tfds.load('horses_or_humans',
                    split='train',
                    as_supervised=True)
    train_batches = data.shuffle(100).batch(10)
    
    ## model define 
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(conv_n,conv_s, activation = h_act_f,
                            input_shape = (300,300,3)),
        tf.keras.layers.MaxPooling2D(maxpool_s),
        tf.keras.layers.Conv2D(conv_n*2,conv_s, activation = h_act_f,
                            input_shape = (300,300,3)),
        tf.keras.layers.MaxPooling2D(maxpool_s),
        tf.keras.layers.Conv2D(conv_n*4,conv_s, activation = h_act_f,
                            input_shape = (300,300,3)),
        tf.keras.layers.MaxPooling2D(maxpool_s),
        tf.keras.layers.Conv2D(conv_n*4,conv_s, activation = h_act_f,
                            input_shape = (300,300,3)),
        tf.keras.layers.MaxPooling2D(maxpool_s),
        tf.keras.layers.Conv2D(conv_n*4,conv_s, activation = h_act_f,
                            input_shape = (300,300,3)),
        tf.keras.layers.MaxPooling2D(maxpool_s),
        
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation =  h_act_f),
        tf.keras.layers.Dense(1,activation='sigmoid')
    ])
    ## model compile 
    model.compile(optimizer ='Adam',
                loss = 'binary_crossentropy',
                metrics = ['accuracy'],
                )
    ## learing 
    # model.fit(train_batches,epochs= 3)
    
    ## validatiaon data load and learning
    val_data= tfds.load('horses_or_humans',
                        split='test',
                        as_supervised=True)
    validation_batches = val_data.batch(32)
    model.fit(train_batches, epochs = 3, validation_data =validation_batches)
hh_classification_tfds()

Epoch 1/3
103/103 ━━━━━━━━━━━━━━━━━━━━ 39s 372ms/step - accuracy: 0.7280 - loss: 7.6964 - val_accuracy: 0.8789 - val_loss: 0.8800
Epoch 2/3
103/103 ━━━━━━━━━━━━━━━━━━━━ 40s 389ms/step - accuracy: 0.9615 - loss: 0.1187 - val_accuracy: 0.8125 - val_loss: 0.8115
Epoch 3/3
103/103 ━━━━━━━━━━━━━━━━━━━━ 37s 357ms/step - accuracy: 0.9373 - loss: 0.1614 - val_accuracy: 0.8477 - val_loss: 2.6990


---
## 4.2.1 특정 버전의 데이터셋 로드하기 
- Major : 레코드형태 변화, 위치벼화
- minor : 동일 데이터, 레코드 특성 추가
- patch : 동일 데이터, 내부구성변화

In [10]:
data, info = tfds.load('horses_or_humans:3.0.0', with_info=True)

---
## 4.3 데이터 증식을 위해 매핑 함수 사용하기 

- IDG 의 from directory 를 사용하지 않기 때문에 tfds

- data에  map 을 이용해서 함수를 적용해주면 된다

In [11]:
data = tfds.load('horses_or_humans',split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)


def augment_images(image,label):
    ## tf.image librayr 이미지 증식에 사용할 수잇는 함수가 많다. 
    # https://oreil.ly/H5LZh
    image =tf.cast(image,tf.float32) ## uint8 -> flaot
    image = (image/255) ## standardization 
    image = tf.image.random_flip_left_right(image)
    return image, label 

train = data.map(augment_images)
train_batches = train.shuffle(100).batch(32)

---
## 4.3.1 텐서플로 애드온 사용하기 
tensorlow_addons가 최소한의 유지 보수만 하다 2024년 5월부로 서비스를 안한다

In [12]:
# !pip install tensorflow-addons

In [13]:


# !pip install "keras<3.0.0" "tensorflow<2.16" "tf-models-official<2.16"
# !pip install tensorflow -U
# !pip install "keras<3.1"
print(yellow(f"tensorflow version : {tf.__version__}"))
# print(yellow(f"keras version : {tf.keras.__version__}"))
def augment_images(image,label):
    # import tensorflow_addons as tfa
    from tensorflow import keras
    image =tf.cast(image,tf.float32)
    image= (image/255.0)
    image = tf.image.random_flip_left_right(image)
    # image =tfa.image.rotate(image,40,interpolation='NEAREST')
    return image,label

train = data.map(augment_images)
train_batches = train.shuffle(100).batch(32)

tensorflow version : 2.17.0


In [14]:
# !pip install --upgrade tensorflow-addons

In [15]:
# !pip uninstall tensorflow_addons -y
# !pip install tensorflow_addons
# import tensorflow_addons as tfa
#tensorlow_addons가 최소한의 유지 보수만 하다 2024년 5월부로 서비스를 안한다

---
## 4.4 사용자 정의 분할 사용하기 
- test, train set 을 사용자가 직접 분할 할수 있다ㅏ.   
- https://oreil.ly/Enqzq  슬라이스 문법 

In [16]:
# data  = tfds.load('cats_vs_dogs',split='train[:10000]', as_supervised=True)
# data  = tfds.load('cats_vs_dogs',split='train[:10000]+train[-1000:]', as_supervised=True)
data  = tfds.load('cats_vs_dogs',split='train[:20%]', as_supervised=True)


In [17]:
train_data =tfds.load('cats_vs_dogs', split='train[:5%]',as_supervised=True)
validation_data = tfds.load('cats_vs_dogs', split='train[88%:90%]',as_supervised=True)
test_data = tfds.load('cats_vs_dogs', split='train[-2%:]',as_supervised=True)
print("train data length : ",tf.data.experimental.cardinality(train_data).numpy() )
print("validation data length: ",tf.data.experimental.cardinality(validation_data).numpy() )
print("test data length",tf.data.experimental.cardinality(test_data).numpy() )



train data length :  1163
validation data length:  465
test data length 465


>fasion mnist 처럼 미리 분할된 데이터 셋은 info 에서 splits 를 사용해 크기 확인가능

In [18]:
train_data,info=tfds.load('fashion_mnist', with_info = True)
print(info.splits['train'].num_examples, info.splits['test'].num_examples)

60000 10000


---
## 4.5 TFRecord 이해하기 

In [19]:
data , info = tfds.load('mnist',with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_dir='/Users/forrestdpark/tensorflow_datasets/mnist/3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
)


In [20]:
import os 
filename = os.path.join(os.path.expanduser('~')+ 
                        '/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001')

from pprint import pprint
raw_dataset = tf.data.TFRecordDataset(filename)
for raw_record in raw_dataset.take(1):
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b"\n\x85\x03\n\xf2\x02\n\x05image\x12\xe8\x02\n\xe5\x02\n\xe2\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc

2024-10-18 11:31:02.077762: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [21]:
# 특성 디스크립션을 만들자. 
feature_description = {
    'image': tf.io.FixedLenFeature([],dtype=tf.string),
    'label': tf.io.FixedLenFeature([],dtype=tf.int64)
    
}

def _parse_function(example_proto):
    ## 위에서 만든 딕셔너리로 입력을 파싱
    return tf.io.parse_single_example(example_proto,feature_description)
parsed_dataset = raw_dataset.map(_parse_function)
for parsed_record in parsed_dataset.take(1):
    pprint((parsed_record))

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc9\x8b55\xe7M\xef\xb0\x04\xc0\xfd&\x89\x01<\xbe\xf9\x0

> 파싱이되면 tfrecord 파일을 읽어서 pillow 같은 라이브러리를 사ㅛㅇ해 png 이미지로 디코딩 가능함. 

---
## 4.6 텐서 플로에서 데이터 관리를 위한 ETL 프로세스 


In [22]:
def ETL_process():
    #Extract(추출), Transform(변환), Load(적재)
    #https://f-lab.kr/insight/understanding-etl-process
    import tensorflow as tf
    import tensorflow_datasets as tfds
    ## model define
    conv_n =16
    conv_s = (3,3) 
    h_act = 'relu'
    mp_s = (2,2)
    model = tf.keras.models.Sequential([
        tf.keras.layers.Rescaling(1./255, input_shape=(300,300,3)),
        tf.keras.layers.RandomRotation(0.11,fill_mode='nearest'),
        tf.keras.layers.RandomTranslation(0.2,0.2,fill_mode ='nearest'),
        tf.keras.layers.RandomZoom(0.2,fill_mode='nearest'),
        tf.keras.layers.RandomFlip('horizontal'),
        tf.keras.layers.Conv2D(conv_n*1, conv_s, activation = h_act),
        tf.keras.layers.MaxPooling2D(mp_s),
        tf.keras.layers.Conv2D(conv_n*2, conv_s, activation = h_act),
        tf.keras.layers.MaxPooling2D(mp_s),
        tf.keras.layers.Conv2D(conv_n*4, conv_s, activation = h_act),
        tf.keras.layers.MaxPooling2D(mp_s),
        tf.keras.layers.Conv2D(conv_n*4, conv_s, activation = h_act),
        tf.keras.layers.MaxPooling2D(mp_s),
        tf.keras.layers.Conv2D(conv_n*4, conv_s, activation = h_act),
        tf.keras.layers.MaxPooling2D(mp_s),
        
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation=h_act),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer ='Adam', loss ='binary_crossentropy', metrics =['accuracy'])
    
    ## 추출 단계 (Extraction)
    data =tfds.load('horses_or_humans',split='train',as_supervised =True)
    val_data  =tfds.load('horses_or_humans', split= 'train', as_supervised=True)
    
    ## 변환단계 (Transform)
    # -> model layer 에서 이루어짐으로 함수 작성필요없음 addon service 가끝나서 이렇게 해야함. 
    train_batches = train.shuffle(100).batch(32)
    validataion_batches = val_data.batch(32)
    
    ## 적재 단계(load )
    history = model.fit(train_batches,epochs= 3, validation_data = validataion_batches)
    return model 
model =ETL_process()

Epoch 1/3
33/33 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - accuracy: 0.5229 - loss: 0.7003 - val_accuracy: 0.5131 - val_loss: 0.6924
Epoch 2/3
33/33 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - accuracy: 0.5368 - loss: 0.6926 - val_accuracy: 0.5131 - val_loss: 0.6925
Epoch 3/3
33/33 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - accuracy: 0.5202 - loss: 0.6928 - val_accuracy: 0.5131 - val_loss: 0.6925


---
## 4.6.1 로드 단계 최적화
- ETL 중 L 에서만 gpu, tpu 가 사용 되므로 병렬 프로세스 (pipe lining) 을 하는 것이 좋다. 
## 4.6.2  ETL 병렬화

In [23]:
train_data = tfds.load('cats_vs_dogs',split='train[:10%]',with_info=True)

def file_extraction_from_tfds(data_name ='cats_vs_dogs'):
    file_pattern = os.path.join(
        os.path.expanduser("~")+
        f'/tensorflow_datasets/{data_name}'
    )
    def listdir_show(file_pattern):
        for order,i in enumerate(os.listdir(file_pattern)):
            # print(order,i)
            if order<2:
                version = i
                
        return version
    version = listdir_show(file_pattern)
    file_pattern =os.path.join(file_pattern,version)
    # listdir_show(file_pattern)
    from glob import glob
    file_pattern = glob(os.path.join(file_pattern, f'{data_name}-train.tfrecord*'))[0]  
    file =tf.data.Dataset.list_files(file_pattern)
    print(file_extraction_from_tfds)
    return file
files =file_extraction_from_tfds()
train_dataset = files.interleave(
    tf.data.TFRecordDataset,
    cycle_length= 4, # 동시에 전처리할 입력 원소 개수 지정
    num_parallel_calls=tf.data.experimental.AUTOTUNE ## 병렬 실행 횟수 지정. cpu 개수에 따라 동적으로 설정
    
)
print(train_dataset)



<function file_extraction_from_tfds at 0x13800f880>
<_ParallelInterleaveDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>


In [24]:
## 레코드를 로드할때 디코딩 하는 매핑 함수 
def read_tfrecord(serialized_example):
    feature_description={
        'image': tf.io.FixedLenFeature((), tf.string,""),
        'label': tf.io.FixedLenFeature((), tf.int64,-1)
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    image = tf.io.decode_jpeg(example['image'], channels= 3)
    image = tf.cast(image, tf.float32)
    image = image/255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

## 병렬화 -> ㅡmultiprocessing cpu 8개 

In [25]:
import multiprocessing
cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
train_dataset = train_dataset.cache() # 메모리에 데이터셋을 캐싱 

8


In [26]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)
model.fit(train_dataset, epochs =5, verbose = 1)

Epoch 1/5
46/46 ━━━━━━━━━━━━━━━━━━━━ 53s 1s/step - accuracy: 0.5032 - loss: 0.6929
Epoch 2/5


2024-10-18 11:34:17.693965: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]


46/46 ━━━━━━━━━━━━━━━━━━━━ 171s 4s/step - accuracy: 0.4749 - loss: 0.6931
Epoch 3/5
46/46 ━━━━━━━━━━━━━━━━━━━━ 152s 3s/step - accuracy: 0.4753 - loss: 0.6929
Epoch 4/5
46/46 ━━━━━━━━━━━━━━━━━━━━ 195s 4s/step - accuracy: 0.4971 - loss: 0.6929
Epoch 5/5
46/46 ━━━━━━━━━━━━━━━━━━━━ 97s 2s/step - accuracy: 0.4995 - loss: 0.6928


2024-10-18 11:44:32.921326: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]
